name: 'KICS (Keeping Infrastructure as Code Secure) Code Analysis'
on:
  workflow_call:
    inputs:
      ENABLE_COMMENTS:
        required: true
        type: boolean
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  kics:
    name: Run KICS Code Analysis
    runs-on: ubuntu-20.04
    outputs:
      kics_status: ${{ steps.kics_scan.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run KICS Scan
        id: kics_scan
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: ${{ inputs.WORKING_DIRECTORY }}
          fail_on: high,medium
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
          ignore_on_exit: results
          enable_comments: ${{ inputs.ENABLE_COMMENTS }}
      - name: Display KICS results
        if: always()
        run: cat myResults/results.json
